name: Helm Publish

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: stefanprodan/helm-gh-pages@master
        with:
          access-token: ${{ secrets.GH_PUBLISH_ACCESS_TOKEN }}
          deploy-branch: media-chart
          charts-folder: charts
          commit_username: dhiaayachi
          commit_email: dhia@ayachi.dev