name: Helm Publish

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: stefanprodan/helm-gh-pages@master
        env:
          VERSION: ${{ github.ref_name }}
        with:
          token: ${{ secrets.GH_PUBLISH_ACCESS_TOKEN }}
          branch: media-chart
          charts_dir: charts
          commit_username: dhiaayachi
          commit_email: dhia@ayachi.dev
          chart_version: ${VERSION#release/v}
