name: Helm Publish

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: J12934/helm-gh-pages-action@master
        with:
          access-token: ${{ secrets.GH_PUBLISH_ACCESS_TOKEN }}
          deploy-branch: media-chart
          charts-folder: .