name: Helm Publish

on:
  push:
    branches:
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: echo "VERSION=$(cut -c 10- <<<${{ github.ref_name }})">>$GITHUB_ENV
      - run: env
      - uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GH_PUBLISH_ACCESS_TOKEN }}
          branch: media-chart
          charts_dir: charts
          commit_username: dhiaayachi
          commit_email: dhia@ayachi.dev
          chart_version: ${VERSION}
